# 模组加载器配置
modLoader="javafml"
loaderVersion="[4.0.39,)"  # 兼容当前 FML 版本

# 模组基本信息
license="All Rights Reserved"
authors="jinyi"
issueTrackerURL="https://no.com/issues"
displayURL="https://no.com/mods/noattack"

[[mods]]
modId="noattack"
version="1.0.0"
displayName="NoAttack Mod"
description='''禁用玩家攻击的模组，适用于 Minecraft 1.21.1 和 NeoForge 21.1.x'''  # 单行字符串，无换行

# 依赖配置
[[dependencies.noattack]]
modId="neoforge"
type="required"
versionRange="[21.1.169,)"  # 明确版本范围，无换行
ordering="AFTER"
side="BOTH"

[[dependencies.noattack]]
modId="minecraft"
type="required"
versionRange="[1.21.1,)"
ordering="NONE"
side="BOTH"

# 可选功能配置（若不需要可删除）
[features.noattack]
openGLVersion="[3.2,)"  # 可选：指定 OpenGL 版本要求